replicaCount: 1
image: quay.io/marjoram/pipeline-operator
tag: latest
pullPolicy:
service:
  enabled: false
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi
rbac:
  install: true
  apiVersion: v1alpha1
  imagePullSecrets: []
