apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "name" . | quote }}
  labels:
    component: pipeline-operator
{{ include "helm-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pipeline-operator
{{ include "common-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: pipeline-operator
{{ include "common-labels" . | indent 8 }}
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: {{ include "name" . | quote }}
{{- end }}
      containers:
      - name: pipeline-operator
        image: {{ include "image" . | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        #ports:
        #- containerPort: 9710
        #  name: metrics
        #  protocol: TCP
